Drop usleep() macro definition for Windows which conflicts with mingw-w64’s compat implementation.
If mowgli.h is #included before the library user #includes unistd.h,
the inclusion of unistd.h from mingw-w64 fails with something like
“unistd.h:35:29: error: expected declaration specifiers or ‘...’
before ‘(’ token”. This fixes the problem by just dropping libmowgli’s
now-unnecessary usleep() compat definition.